/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.COdontograma;
import java.awt.Color;
import modelo.*;

/**
 *
 * @author jdfer
 */
public class Odontograma extends javax.swing.JFrame {
    COdontograma controlOdontograma;
    /**
     * Creates new form Odontograma
     */
    public Odontograma() {
        initComponents();
        this.controlOdontograma = new COdontograma();
        controlOdontograma.esconderMarcas(labelExtraccion18, labelAusente18, labelEmpaquetamiento18, labelCG18, labelCaries18, labelCariesD18, 
                                            labelSurco18, labelMovilidad18);
    }

    public Odontograma(Odontologo odontologo, String cedula, String nombre, String edad){
        initComponents();
        this.controlOdontograma = new COdontograma();
        controlOdontograma.esconderMarcas(labelExtraccion18, labelAusente18, labelEmpaquetamiento18, label18, labelCaries18, labelCariesD18,
                                            labelSurco18, labelMovilidad18);
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        panelDatosConsulta = new javax.swing.JPanel();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelHM = new javax.swing.JLabel();
        labelFechaConsulta = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        labelTratamiento = new javax.swing.JLabel();
        labelDienteActual = new javax.swing.JLabel();
        scrollTxtArea = new javax.swing.JScrollPane();
        txtAreaTratamiento = new javax.swing.JTextArea();
        panelBotones = new javax.swing.JPanel();
        botonExtraccion = new javax.swing.JButton();
        botonAusente = new javax.swing.JButton();
        botonCaries = new javax.swing.JButton();
        botonE = new javax.swing.JButton();
        botonSurco = new javax.swing.JButton();
        botonGingival = new javax.swing.JButton();
        botonMovilidadI = new javax.swing.JButton();
        botonMovilidadII = new javax.swing.JButton();
        botonMovilidadIII = new javax.swing.JButton();
        botonMovilidadIV = new javax.swing.JButton();
        botonCariesR = new javax.swing.JButton();
        label18 = new javax.swing.JLabel();
        labelEmpaquetamiento18 = new javax.swing.JLabel();
        labelMovilidad18 = new javax.swing.JLabel();
        labelExtraccion18 = new javax.swing.JLabel();
        labelSurco18 = new javax.swing.JLabel();
        labelCariesD18 = new javax.swing.JLabel();
        labelCaries18 = new javax.swing.JLabel();
        labelAusente18 = new javax.swing.JLabel();
        labelCG18 = new javax.swing.JLabel();
        labelOdontograma = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(0, 102, 204));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Nirmala UI", 0, 60)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Odontograma");

        labelUsuario.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Nombre de usuario:");

        labelFecha.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("Fecha:");

        botonSalir.setBackground(new java.awt.Color(255, 51, 51));
        botonSalir.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(23, 23, 23))
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(301, Short.MAX_VALUE))))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addComponent(botonSalir)
                        .addGap(30, 30, 30))
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTitulo)
                        .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 90));

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosConsulta.setBackground(new java.awt.Color(65, 155, 224));

        labelCedula.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(255, 255, 255));
        labelCedula.setText("CI: 28163726");

        labelNombre.setBackground(new java.awt.Color(255, 255, 255));
        labelNombre.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre: Juan Fernández");

        labelHM.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        labelHM.setForeground(new java.awt.Color(255, 255, 255));
        labelHM.setText("N° Historia Médica: 12993");

        labelFechaConsulta.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        labelFechaConsulta.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaConsulta.setText("Fecha: 11/11/22");

        labelEdad.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(255, 255, 255));
        labelEdad.setText("Edad: 20");

        javax.swing.GroupLayout panelDatosConsultaLayout = new javax.swing.GroupLayout(panelDatosConsulta);
        panelDatosConsulta.setLayout(panelDatosConsultaLayout);
        panelDatosConsultaLayout.setHorizontalGroup(
            panelDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosConsultaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelNombre)
                .addGap(86, 86, 86)
                .addComponent(labelCedula)
                .addGap(84, 84, 84)
                .addComponent(labelHM)
                .addGap(84, 84, 84)
                .addComponent(labelEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(labelFechaConsulta)
                .addGap(52, 52, 52))
        );
        panelDatosConsultaLayout.setVerticalGroup(
            panelDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedula)
                    .addComponent(labelNombre)
                    .addComponent(labelFechaConsulta)
                    .addComponent(labelEdad)
                    .addComponent(labelHM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelInfo.add(panelDatosConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1340, -1));

        botonGuardar.setBackground(new java.awt.Color(102, 153, 255));
        botonGuardar.setFont(new java.awt.Font("Nirmala UI", 0, 20)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save icon.png"))); // NOI18N
        botonGuardar.setText("Guardar odontograma");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        panelInfo.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 620, -1, 50));

        labelTratamiento.setFont(new java.awt.Font("Nirmala UI", 0, 30)); // NOI18N
        labelTratamiento.setText("Tratamiento");
        panelInfo.add(labelTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 200, 50));

        labelDienteActual.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 30)); // NOI18N
        labelDienteActual.setText("32. 123456789876543");
        panelInfo.add(labelDienteActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 470, 50));

        txtAreaTratamiento.setColumns(20);
        txtAreaTratamiento.setRows(5);
        scrollTxtArea.setViewportView(txtAreaTratamiento);

        panelInfo.add(scrollTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 540, 150));

        panelBotones.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));

        botonExtraccion.setBackground(new java.awt.Color(255, 255, 255));
        botonExtraccion.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        botonExtraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/extraccion icon.png"))); // NOI18N
        botonExtraccion.setPreferredSize(new java.awt.Dimension(64, 64));
        botonExtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExtraccionActionPerformed(evt);
            }
        });

        botonAusente.setBackground(new java.awt.Color(255, 255, 255));
        botonAusente.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        botonAusente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ausente icon.png"))); // NOI18N
        botonAusente.setPreferredSize(new java.awt.Dimension(64, 64));
        botonAusente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAusenteActionPerformed(evt);
            }
        });

        botonCaries.setBackground(new java.awt.Color(255, 255, 255));
        botonCaries.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        botonCaries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo rojo 32.png"))); // NOI18N
        botonCaries.setPreferredSize(new java.awt.Dimension(64, 64));
        botonCaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCariesActionPerformed(evt);
            }
        });

        botonE.setBackground(new java.awt.Color(255, 255, 255));
        botonE.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 30)); // NOI18N
        botonE.setText("E");
        botonE.setPreferredSize(new java.awt.Dimension(64, 64));
        botonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEActionPerformed(evt);
            }
        });

        botonSurco.setBackground(new java.awt.Color(255, 255, 255));
        botonSurco.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        botonSurco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo verde.png"))); // NOI18N
        botonSurco.setPreferredSize(new java.awt.Dimension(64, 64));
        botonSurco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSurcoActionPerformed(evt);
            }
        });

        botonGingival.setBackground(new java.awt.Color(255, 255, 255));
        botonGingival.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        botonGingival.setForeground(new java.awt.Color(255, 0, 0));
        botonGingival.setText("~");
        botonGingival.setPreferredSize(new java.awt.Dimension(64, 64));
        botonGingival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGingivalActionPerformed(evt);
            }
        });

        botonMovilidadI.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        botonMovilidadI.setText("I");
        botonMovilidadI.setPreferredSize(new java.awt.Dimension(30, 30));
        botonMovilidadI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMovilidadIActionPerformed(evt);
            }
        });

        botonMovilidadII.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        botonMovilidadII.setText("II");
        botonMovilidadII.setPreferredSize(new java.awt.Dimension(30, 30));
        botonMovilidadII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMovilidadIIActionPerformed(evt);
            }
        });

        botonMovilidadIII.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        botonMovilidadIII.setText("III");
        botonMovilidadIII.setPreferredSize(new java.awt.Dimension(30, 30));
        botonMovilidadIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMovilidadIIIActionPerformed(evt);
            }
        });

        botonMovilidadIV.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        botonMovilidadIV.setText("IV");
        botonMovilidadIV.setPreferredSize(new java.awt.Dimension(30, 30));
        botonMovilidadIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMovilidadIVActionPerformed(evt);
            }
        });

        botonCariesR.setBackground(new java.awt.Color(255, 255, 255));
        botonCariesR.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        botonCariesR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caries detenida 32.png"))); // NOI18N
        botonCariesR.setPreferredSize(new java.awt.Dimension(64, 64));
        botonCariesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCariesRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCariesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAusente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonSurco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonMovilidadI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMovilidadII, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMovilidadIII, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMovilidadIV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonGingival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonAusente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSurco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCaries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCariesR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(botonMovilidadI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonMovilidadII, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonMovilidadIII, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(botonMovilidadIV, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGingival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        panelInfo.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 540, 210));

        label18.setToolTipText("");
        label18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label18MouseClicked(evt);
            }
        });
        panelInfo.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 120));

        labelEmpaquetamiento18.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 35)); // NOI18N
        labelEmpaquetamiento18.setText("E");
        panelInfo.add(labelEmpaquetamiento18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, 60));

        labelMovilidad18.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 35)); // NOI18N
        labelMovilidad18.setText("IV");
        panelInfo.add(labelMovilidad18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 30, 60));

        labelExtraccion18.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 90)); // NOI18N
        labelExtraccion18.setForeground(new java.awt.Color(255, 0, 0));
        labelExtraccion18.setText("X");
        panelInfo.add(labelExtraccion18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, 90));

        labelSurco18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo verde 16.png"))); // NOI18N
        panelInfo.add(labelSurco18, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 270, 20, 50));

        labelCariesD18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caries detenida 32.png"))); // NOI18N
        panelInfo.add(labelCariesD18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 50));

        labelCaries18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo rojo 32.png"))); // NOI18N
        panelInfo.add(labelCaries18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 50));

        labelAusente18.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 120)); // NOI18N
        labelAusente18.setForeground(new java.awt.Color(52, 152, 219));
        labelAusente18.setText("l");
        panelInfo.add(labelAusente18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 30, 120));

        labelCG18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 80)); // NOI18N
        labelCG18.setForeground(new java.awt.Color(255, 0, 0));
        labelCG18.setText("~");
        panelInfo.add(labelCG18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 60));

        labelOdontograma.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 30)); // NOI18N
        labelOdontograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/odontograma.jpg"))); // NOI18N
        labelOdontograma.setText("IV");
        panelInfo.add(labelOdontograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 760, 470));

        getContentPane().add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 1340, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonExtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExtraccionActionPerformed
        botonExtraccion.setSelected(true);
    }//GEN-LAST:event_botonExtraccionActionPerformed

    private void botonAusenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAusenteActionPerformed
        botonAusente.setSelected(true);
    }//GEN-LAST:event_botonAusenteActionPerformed

    private void botonCariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCariesActionPerformed
        botonCaries.setSelected(true);
    }//GEN-LAST:event_botonCariesActionPerformed

    private void botonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEActionPerformed
        botonE.setSelected(true);
    }//GEN-LAST:event_botonEActionPerformed

    private void botonSurcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSurcoActionPerformed
        botonSurco.setSelected(true);
    }//GEN-LAST:event_botonSurcoActionPerformed

    private void botonGingivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGingivalActionPerformed
        botonGingival.setSelected(true);
    }//GEN-LAST:event_botonGingivalActionPerformed

    private void label18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label18MouseClicked
        controlOdontograma.seleccionDiente(labelExtraccion18, labelAusente18, labelEmpaquetamiento18, labelCG18, labelCaries18, labelCariesD18,
                                            labelSurco18, labelMovilidad18, botonExtraccion, botonAusente, botonE, botonGingival, 
                                            botonCaries, botonCariesR, botonSurco,botonMovilidadI,botonMovilidadII,botonMovilidadIII,
                                            botonMovilidadIV);
    }//GEN-LAST:event_label18MouseClicked

    private void botonMovilidadIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMovilidadIActionPerformed
        botonMovilidadI.setSelected(true);
    }//GEN-LAST:event_botonMovilidadIActionPerformed

    private void botonMovilidadIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMovilidadIIActionPerformed
        botonMovilidadII.setSelected(true);
    }//GEN-LAST:event_botonMovilidadIIActionPerformed

    private void botonMovilidadIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMovilidadIIIActionPerformed
        botonMovilidadIII.setSelected(true);
    }//GEN-LAST:event_botonMovilidadIIIActionPerformed

    private void botonMovilidadIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMovilidadIVActionPerformed
        botonMovilidadIV.setSelected(true);
    }//GEN-LAST:event_botonMovilidadIVActionPerformed

    private void botonCariesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCariesRActionPerformed
        botonCariesR.setSelected(true);
    }//GEN-LAST:event_botonCariesRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odontograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAusente;
    private javax.swing.JButton botonCaries;
    private javax.swing.JButton botonCariesR;
    private javax.swing.JButton botonE;
    private javax.swing.JButton botonExtraccion;
    private javax.swing.JButton botonGingival;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonMovilidadI;
    private javax.swing.JButton botonMovilidadII;
    private javax.swing.JButton botonMovilidadIII;
    private javax.swing.JButton botonMovilidadIV;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSurco;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel labelAusente18;
    private javax.swing.JLabel labelCG18;
    private javax.swing.JLabel labelCaries18;
    private javax.swing.JLabel labelCariesD18;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelDienteActual;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEmpaquetamiento18;
    private javax.swing.JLabel labelExtraccion18;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFechaConsulta;
    private javax.swing.JLabel labelHM;
    private javax.swing.JLabel labelMovilidad18;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelOdontograma;
    private javax.swing.JLabel labelSurco18;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTratamiento;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatosConsulta;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollTxtArea;
    private javax.swing.JTextArea txtAreaTratamiento;
    // End of variables declaration//GEN-END:variables
}
