/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author jdfer
 */
public class RegistrarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarConsulta
     */
    public RegistrarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonDatosPersonales = new javax.swing.JButton();
        botonExamenSub = new javax.swing.JButton();
        botonAntecedentes = new javax.swing.JButton();
        botonExamenCli = new javax.swing.JButton();
        botonExamenCom = new javax.swing.JButton();
        botonDiaTra = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        pestRegistrar = new javax.swing.JTabbedPane();
        pestDatosPersonales = new javax.swing.JPanel();
        labelDatosPersonales = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelOcupacion = new javax.swing.JLabel();
        labelLugarNacimiento = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        labelReferencia = new javax.swing.JLabel();
        labelEstudiante = new javax.swing.JLabel();
        labelHistoriaMedica = new javax.swing.JLabel();
        pestExamenSub = new javax.swing.JPanel();
        labelDatosPersonales1 = new javax.swing.JLabel();
        labelMotivo = new javax.swing.JLabel();
        labelCursoEnfermedad = new javax.swing.JLabel();
        labelMedicamento = new javax.swing.JLabel();
        labelCual = new javax.swing.JLabel();
        labelHospitalizado = new javax.swing.JLabel();
        labelPorQue = new javax.swing.JLabel();
        labelQuirurgicamente = new javax.swing.JLabel();
        labelFumaUd = new javax.swing.JLabel();
        labelDesdeCuando = new javax.swing.JLabel();
        labelCuantosCigarrillos = new javax.swing.JLabel();
        labelTomaUd = new javax.swing.JLabel();
        labelQueCantidad = new javax.swing.JLabel();
        scrollAntecedentes = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelDatosPersonales3 = new javax.swing.JLabel();
        pestExamenClin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pestExamenCom = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pestDiaTra = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(javax.swing.UIManager.getDefaults().getColor("Tree.selectionBackground"));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Nirmala UI", 0, 60)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Registrar consulta");

        labelUsuario.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Nombre de usuario");

        labelFecha.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("Fecha");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        panelBotones.setBackground(java.awt.SystemColor.activeCaption);
        panelBotones.setForeground(javax.swing.UIManager.getDefaults().getColor("TextArea.selectionBackground"));

        botonDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));
        botonDatosPersonales.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonDatosPersonales.setText("Datos personales");
        botonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDatosPersonalesActionPerformed(evt);
            }
        });

        botonExamenSub.setBackground(new java.awt.Color(255, 255, 255));
        botonExamenSub.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonExamenSub.setText("Examen subjetivo");
        botonExamenSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExamenSubActionPerformed(evt);
            }
        });

        botonAntecedentes.setBackground(new java.awt.Color(255, 255, 255));
        botonAntecedentes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonAntecedentes.setText("Antecedentes");
        botonAntecedentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAntecedentesActionPerformed(evt);
            }
        });

        botonExamenCli.setBackground(new java.awt.Color(255, 255, 255));
        botonExamenCli.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonExamenCli.setText("Examen clínico");
        botonExamenCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExamenCliActionPerformed(evt);
            }
        });

        botonExamenCom.setBackground(new java.awt.Color(255, 255, 255));
        botonExamenCom.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonExamenCom.setText("Exámenes complementarios");
        botonExamenCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExamenComActionPerformed(evt);
            }
        });

        botonDiaTra.setBackground(new java.awt.Color(255, 255, 255));
        botonDiaTra.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        botonDiaTra.setText("Diagnóstico y Tratamiento");
        botonDiaTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiaTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonDatosPersonales)
                .addGap(10, 10, 10)
                .addComponent(botonExamenSub)
                .addGap(10, 10, 10)
                .addComponent(botonAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botonExamenCli, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botonExamenCom)
                .addGap(10, 10, 10)
                .addComponent(botonDiaTra)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonExamenSub)
                        .addComponent(botonDatosPersonales))
                    .addComponent(botonAntecedentes)
                    .addComponent(botonExamenCli)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonExamenCom)
                        .addComponent(botonDiaTra))))
        );

        getContentPane().add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 70));

        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pestDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));

        labelDatosPersonales.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        labelDatosPersonales.setText("I. Datos Personales");

        labelCedula.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelCedula.setText("Cédula:");

        labelNombre.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelNombre.setText("Nombre y apellido:");

        labelSexo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelSexo.setText("Sexo:");

        labelEdad.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelEdad.setText("Edad:");

        labelTelefono.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelTelefono.setText("Teléfono:");

        labelOcupacion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelOcupacion.setText("Ocupación:");

        labelLugarNacimiento.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelLugarNacimiento.setText("Lugar de nacimiento:");

        labelDomicilio.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelDomicilio.setText("Domicilio:");

        labelReferencia.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelReferencia.setText("Referencia:");

        labelEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelEstudiante.setText("Estudiante:");

        labelHistoriaMedica.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelHistoriaMedica.setText("Historia médica:");

        javax.swing.GroupLayout pestDatosPersonalesLayout = new javax.swing.GroupLayout(pestDatosPersonales);
        pestDatosPersonales.setLayout(pestDatosPersonalesLayout);
        pestDatosPersonalesLayout.setHorizontalGroup(
            pestDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestDatosPersonalesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pestDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDomicilio)
                    .addComponent(labelLugarNacimiento)
                    .addComponent(labelEstudiante)
                    .addComponent(labelReferencia)
                    .addComponent(labelNombre)
                    .addComponent(labelOcupacion)
                    .addGroup(pestDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(labelTelefono)
                        .addGap(280, 280, 280)
                        .addComponent(labelEdad)
                        .addGap(156, 156, 156)
                        .addComponent(labelSexo))
                    .addComponent(labelHistoriaMedica)
                    .addComponent(labelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCedula))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        pestDatosPersonalesLayout.setVerticalGroup(
            pestDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatosPersonales)
                .addGap(40, 40, 40)
                .addComponent(labelCedula)
                .addGap(18, 18, 18)
                .addComponent(labelHistoriaMedica)
                .addGap(48, 48, 48)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pestDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(labelEdad)
                    .addComponent(labelSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(labelLugarNacimiento)
                .addGap(18, 18, 18)
                .addComponent(labelDomicilio)
                .addGap(45, 45, 45)
                .addComponent(labelOcupacion)
                .addGap(18, 18, 18)
                .addComponent(labelEstudiante)
                .addGap(18, 18, 18)
                .addComponent(labelReferencia)
                .addGap(90, 90, 90))
        );

        pestRegistrar.addTab("tab1", pestDatosPersonales);

        pestExamenSub.setBackground(new java.awt.Color(255, 255, 255));

        labelDatosPersonales1.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        labelDatosPersonales1.setText("II. Examen subjetivo");

        labelMotivo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelMotivo.setText("Motivo de consulta:");

        labelCursoEnfermedad.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelCursoEnfermedad.setText("Curso de la enfermedad actual:");

        labelMedicamento.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelMedicamento.setText("¿Está tomando algún medicamento?:");

        labelCual.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelCual.setText("¿Cuál?:");

        labelHospitalizado.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelHospitalizado.setText("¿Ha sido hospitalizado alguna vez?:");

        labelPorQue.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelPorQue.setText("¿Por qué?:");

        labelQuirurgicamente.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelQuirurgicamente.setText("¿Ha sido intervenido quirúrgicamente?:");

        labelFumaUd.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelFumaUd.setText("Fuma ud:");

        labelDesdeCuando.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelDesdeCuando.setText("¿Desde cuándo?:");

        labelCuantosCigarrillos.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelCuantosCigarrillos.setText("¿Cuántos cigarrillos?:");

        labelTomaUd.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelTomaUd.setText("Toma ud:");

        labelQueCantidad.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        labelQueCantidad.setText("¿Qué cantidad?:");

        javax.swing.GroupLayout pestExamenSubLayout = new javax.swing.GroupLayout(pestExamenSub);
        pestExamenSub.setLayout(pestExamenSubLayout);
        pestExamenSubLayout.setHorizontalGroup(
            pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenSubLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuirurgicamente)
                    .addComponent(labelMotivo)
                    .addComponent(labelDatosPersonales1)
                    .addGroup(pestExamenSubLayout.createSequentialGroup()
                        .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pestExamenSubLayout.createSequentialGroup()
                                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMedicamento)
                                    .addComponent(labelHospitalizado)
                                    .addComponent(labelCursoEnfermedad))
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestExamenSubLayout.createSequentialGroup()
                                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFumaUd)
                                    .addComponent(labelTomaUd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelQueCantidad)
                                    .addComponent(labelCuantosCigarrillos))
                                .addGap(160, 160, 160)))
                        .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPorQue)
                            .addComponent(labelCual)
                            .addComponent(labelDesdeCuando))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pestExamenSubLayout.setVerticalGroup(
            pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatosPersonales1)
                .addGap(50, 50, 50)
                .addComponent(labelMotivo)
                .addGap(40, 40, 40)
                .addComponent(labelCursoEnfermedad)
                .addGap(40, 40, 40)
                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedicamento)
                    .addComponent(labelCual))
                .addGap(40, 40, 40)
                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHospitalizado)
                    .addComponent(labelPorQue))
                .addGap(40, 40, 40)
                .addComponent(labelQuirurgicamente)
                .addGap(40, 40, 40)
                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFumaUd)
                    .addComponent(labelDesdeCuando)
                    .addComponent(labelCuantosCigarrillos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pestExamenSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTomaUd)
                    .addComponent(labelQueCantidad))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pestRegistrar.addTab("tab3", pestExamenSub);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 764));

        labelDatosPersonales3.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        labelDatosPersonales3.setText("III. Antecedentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelDatosPersonales3)
                .addContainerGap(926, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDatosPersonales3)
                .addContainerGap(843, Short.MAX_VALUE))
        );

        scrollAntecedentes.setViewportView(jPanel1);

        pestRegistrar.addTab("tab7", scrollAntecedentes);

        pestExamenClin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Pestaña 4");

        javax.swing.GroupLayout pestExamenClinLayout = new javax.swing.GroupLayout(pestExamenClin);
        pestExamenClin.setLayout(pestExamenClinLayout);
        pestExamenClinLayout.setHorizontalGroup(
            pestExamenClinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenClinLayout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(jLabel4)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        pestExamenClinLayout.setVerticalGroup(
            pestExamenClinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenClinLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel4)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        pestRegistrar.addTab("tab4", pestExamenClin);

        pestExamenCom.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Pestaña 5");

        javax.swing.GroupLayout pestExamenComLayout = new javax.swing.GroupLayout(pestExamenCom);
        pestExamenCom.setLayout(pestExamenComLayout);
        pestExamenComLayout.setHorizontalGroup(
            pestExamenComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenComLayout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(jLabel5)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        pestExamenComLayout.setVerticalGroup(
            pestExamenComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestExamenComLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel5)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        pestRegistrar.addTab("tab5", pestExamenCom);

        pestDiaTra.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Pestaña 6");

        javax.swing.GroupLayout pestDiaTraLayout = new javax.swing.GroupLayout(pestDiaTra);
        pestDiaTra.setLayout(pestDiaTraLayout);
        pestDiaTraLayout.setHorizontalGroup(
            pestDiaTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestDiaTraLayout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(jLabel6)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        pestDiaTraLayout.setVerticalGroup(
            pestDiaTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestDiaTraLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel6)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        pestRegistrar.addTab("tab6", pestDiaTra);

        panelInfo.add(pestRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -29, -1, 670));

        getContentPane().add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1200, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAntecedentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAntecedentesActionPerformed
        pestRegistrar.setSelectedIndex(2);
    }//GEN-LAST:event_botonAntecedentesActionPerformed

    private void botonExamenSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExamenSubActionPerformed
        pestRegistrar.setSelectedIndex(1);
    }//GEN-LAST:event_botonExamenSubActionPerformed

    private void botonExamenCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExamenCliActionPerformed
        pestRegistrar.setSelectedIndex(3);
    }//GEN-LAST:event_botonExamenCliActionPerformed

    private void botonExamenComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExamenComActionPerformed
        pestRegistrar.setSelectedIndex(4);
    }//GEN-LAST:event_botonExamenComActionPerformed

    private void botonDiaTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiaTraActionPerformed
        pestRegistrar.setSelectedIndex(5);
    }//GEN-LAST:event_botonDiaTraActionPerformed

    private void botonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosPersonalesActionPerformed
        pestRegistrar.setSelectedIndex(0);
    }//GEN-LAST:event_botonDatosPersonalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAntecedentes;
    private javax.swing.JButton botonDatosPersonales;
    private javax.swing.JButton botonDiaTra;
    private javax.swing.JButton botonExamenCli;
    private javax.swing.JButton botonExamenCom;
    private javax.swing.JButton botonExamenSub;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCual;
    private javax.swing.JLabel labelCuantosCigarrillos;
    private javax.swing.JLabel labelCursoEnfermedad;
    private javax.swing.JLabel labelDatosPersonales;
    private javax.swing.JLabel labelDatosPersonales1;
    private javax.swing.JLabel labelDatosPersonales3;
    private javax.swing.JLabel labelDesdeCuando;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEstudiante;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFumaUd;
    private javax.swing.JLabel labelHistoriaMedica;
    private javax.swing.JLabel labelHospitalizado;
    private javax.swing.JLabel labelLugarNacimiento;
    private javax.swing.JLabel labelMedicamento;
    private javax.swing.JLabel labelMotivo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelOcupacion;
    private javax.swing.JLabel labelPorQue;
    private javax.swing.JLabel labelQueCantidad;
    private javax.swing.JLabel labelQuirurgicamente;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTomaUd;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel pestDatosPersonales;
    private javax.swing.JPanel pestDiaTra;
    private javax.swing.JPanel pestExamenClin;
    private javax.swing.JPanel pestExamenCom;
    private javax.swing.JPanel pestExamenSub;
    private javax.swing.JTabbedPane pestRegistrar;
    private javax.swing.JScrollPane scrollAntecedentes;
    // End of variables declaration//GEN-END:variables
}
